### ISSUE TITLE
RTU 'not found, using placeholder'

### ISSUE THREAD

**Issue by Vasolix** [MikaylaFischler/cc-mek-scada#191]
Hello,
I can't connect my turbine / matrix / boiler I'm probably doing something wrong

**Screenshots and Logs**
[Mon Mar 13 21:17:37 2023] [INF] ========================================
[Mon Mar 13 21:17:37 2023] [INF] BOOTING rtu.startup v0.13.0
[Mon Mar 13 21:17:37 2023] [INF] ========================================
[Mon Mar 13 21:17:37 2023] [INF] PPM: found a modem (top)
[Mon Mar 13 21:17:37 2023] [INF] PPM: found a inductionPort (left)
[Mon Mar 13 21:17:37 2023] [WRN] configure> 'inductionPort_1' not found, using placeholder
[Mon Mar 13 21:17:37 2023] [INF] PPM: mount_virtual() -> allocated new virtual device ppm_vdev_0
[Mon Mar 13 21:17:37 2023] [INF] configure> initialized RTU unit # 1: inductionPort_1 (virtual) [1] for facility
[Mon Mar 13 21:17:37 2023] [INF] startup> completed

**Comment by MikaylaFischler** [comment]
It looks like the computer is touching the induction port on it's left side, so since its directly contacting it and not through a modem, it would just be the side (in this case left): `found a inductionPort (left)`

If it was on a modem network when you connect it it would say what it's network name is, like `inductionPort_1`, but that isn't the case here. You'll always be using whatever the name is in the parenthesis in those found messages, I'll update the wiki to add that detail
