### ISSUE TITLE
Fresh install of supervisor fails

### ISSUE THREAD

**Issue by badgeminer** [MikaylaFischler/cc-mek-scada#257]
**Describe the bug**
Fresh install of supervisor fails with `'graphics.core' not found`

**Expected behavior**
It works

**Comment by MikaylaFischler** [comment]
Install manifest deployment was out-of-date, it should work now.

**Comment by MikaylaFischler** [comment]
Updates after failing an install with this issue currently won't work because graphics itself isn't versioned, so it'll see the supervisor version is the same and skip it. This is an edge case since normally I increment software versions when graphics change, but this is due to it not listing graphics as required. I'll revisit this with the next version of the installer since it seems to be a problem, I should probably just version the graphics library.

**Comment by MikaylaFischler** [comment]
Issue mitigated this time around now, I've updated the supervisor version. GitHub actions will now deploy the latest manifest for the new installer. `update` and `install` options will now work.
