### ISSUE TITLE
System Start/Stop in Pocket

### ISSUE THREAD

**Issue by pierrei** [MikaylaFischler/cc-mek-scada#355]
Thanks for putting this project together - it's one of the coolest things I've seen in a while!

I'd love to be able to start/stop the automatic process control from my pocket computer. A first step could be as easy as just add the start/stop button to the pocket computer without showing any statuses. Next step could be to display the status of the system as well. This can for sure be extended to display the error that scrammed the system and also allow for a ack and a reset, but that can come later.

Would be so amazing to be able to start stop while walking around checking things!

**Comment by MikaylaFischler** [comment]
Thanks!!

And that's the plan! The CTL "app" on the pocket home page is where the controls for auto control will be once I get to them. There will be auto start/stop, auto mode change, and inputs for the burn/charge/generation targets.

The pocket app will be getting more development focus shortly, likely either in the next release alongside the RTU configurator tool or afterwards, depending on how long that configurator takes. I'm intending on adding view information before control information though, since I think it would be better to provide controls only once I can indicate if everything is okay or not. Depending on how long things take to develop though, I may add it earlier than planned since you asked.

**Comment by pierrei** [comment]
Cool! I personally feel the control functions on the system are so reliable I don't actually have to see any statuses before starting it up again, since if something goes wrong it'll stop by itself. But for sure, more information is better!
