### ISSUE TITLE
Colorblind-Independent Color Accessibility Modifiers

### ISSUE THREAD

**Issue by underscorched** [MikaylaFischler/cc-mek-scada#457]
**Is your feature request related to a problem? Please describe.**
While I'm not colorblind myself, I think it would be a good idea to separate the color accessibility options from having a colorblindness mode enabled.

**Describe the solution you'd like**
The ability to independently enable the "blue good", "black off", and network light verbosity regardless of colorblindness mode. The colorblindness modes can still toggle these on, but it shouldn't be required. Maybe vice versa as well.

**Comment by MikaylaFischler** [comment]
I like that idea! I think it would be the least intrusive in the code if I added an additional color mode that did blue/black/network light change all as one, which sounds like it might be what you're asking. In my testing I thought the blue on black indicators looked really clean so I'm happy to make that accessible without shifting the other colors around. The basalt theme on front panels with blue indicators is very aesthetically pleasing.

I think I will leave the colorblindness stuff as-is though and not make it a vice versa change, since the blue and network light changes are critical to that and the black off was only added because it helped a lot with contrast in Tritanopia mode (and the others benefited too).

**Comment by underscorched** [comment]
Fine enough for me.

**Comment by MikaylaFischler** [comment]
Ended up landing on this

<img width="609" alt="image" src="https://github.com/MikaylaFischler/cc-mek-scada/assets/2926271/c03409f2-9ac1-4f93-88af-5f64a9e6a035">
<img width="609" alt="image" src="https://github.com/MikaylaFischler/cc-mek-scada/assets/2926271/0d516fa2-7e18-4059-97d8-cd6f6b4ebe57">
<img width="609" alt="image" src="https://github.com/MikaylaFischler/cc-mek-scada/assets/2926271/80ad52b3-c9a5-4c80-94b7-cbf80a226461">
<img width="609" alt="image" src="https://github.com/MikaylaFischler/cc-mek-scada/assets/2926271/fc5c50d3-3c75-455e-8748-7866e0934aed">
