### ISSUE TITLE
Reactor PLC PPM Crash on Server Boot

### ISSUE THREAD

**Issue by Sharparam** [MikaylaFischler/cc-mek-scada#476]
**Describe the bug**
Shut down the server yesterday with everything in a working (idle) state, and booted it up today. Immediately there was a warning about reactor lost, which was apparently because the PLC crashed.

**To Reproduce**
Unsure exactly how to reproduce it since this seemed like a chance happening, but recent things I did before shutting down the server yesterday:

Matrix reached full charge while everything was on auto control, and scrammed the reactor properly.

To experiment, I put the reactor in manual control and let it run until it was scrammed due to the turbine energy buffer filling.

Reset all the warnings and left it all on idle before shutting down the server.

Booted server up the following day, with the PLC crashing on load.

**Expected behavior**
PLC boots normally.

**Screenshots and Logs**
Relevant section from the PLC log.txt:
https://gist.github.com/Sharparam/588688aeda1abcad5e64e8fef9668dfb

The supervisor log as it disappears:

```
[Tue Apr 16 21:00:18 2024] [INF] PLC_ESTABLISH: PLC (v1.7.9) [@4] reactor unit 1 PLC connected with session ID 0
[Tue Apr 16 21:00:23 2024] [INF] plc_session(0): session closed by server
[Tue Apr 16 21:00:23 2024] [INF] UNIT 1 ALARM 3 (ReactorLost): TRIPPED [PRIORITY TIMELY]
```

**Additional context**
 - Recently updated to the latest release.
 - All chunks containing reactor and SCADA systems are chunkloaded.
 - Minecraft version: 1.20.4
 - NeoForge version: 20.4.232
 - Mekanism version: 10.5.19
 - CC: Tweaked version: 1.110.2
 - cc-mek-scada versions:
   - PLC: 1.7.9
   - RTUs: 1.9.4
   - Coordinator: 1.4.2
   - Supervisor: 1.3.6

**Comment by MikaylaFischler** [comment]
Thanks for the report!

These startup issues are hard to test since they can be inconsistent. I wasn't able to get this to happen when I tested the change a while back, but this issue is glaringly obvious looking at my code:

The fault counter isn't initialized to zero if it does the `initialized previously undefined field`, only when the function was present at startup. I'm surprised that didn't happen to me, so thanks again. The fix will be on the `devel` branch shortly and included in the next release.
